### ISSUE TITLE
Add a page-level “···” menu for useful actions

### ISSUE THREAD

**Issue by EllisMorrow** [martinkoutecky/tine#182]
### What would you like Tine to do?

Add a “···” menu in the top-right corner of each page. It should provide one consistent place for common page actions, file actions, layout controls, and a few important application links.

The menu should be ordered roughly by expected frequency and grouped so that it remains easy to scan.

Suggested structure:

- Find in page
- Find and replace
- Toggle source mode / rendered mode
- Open in split
  - Open to the right
  - Open below
  - Open to the left
  - Open above
- Open in right sidebar
- Copy
  - Copy page reference
  - Copy page URL
  - Copy relative file path
  - Copy absolute file path
  - Copy page title
- Outline
  - Collapse all
  - Expand all
- Add to favorites / Remove from favorites
- Rename page
- Enter focus mode
- Page information
- Copy / export as…
  - Copy as Markdown
  - Copy as plain text
  - Copy as HTML
  - Export as Markdown
  - Export as HTML
  - Export as PDF, if supported later
- Open with default application
- Show in File Explorer / Finder
- Delete page

Less frequent application-level items can appear near the bottom in separate groups:

- Plugins, when available
- Themes, when available
- Settings
- Community
- Report a bug
- Request a feature

The menu should follow these principles:

- frequently used page actions should appear first;
- related actions should use submenus instead of making one very long list;
- the order should remain stable so users can build muscle memory;
- actions that are unavailable for the current page should be disabled with a short explanation instead of disappearing;
- destructive actions such as deleting a page should stay near the bottom and require confirmation;
- existing Tine functions should be added to this menu first, while missing functions can be implemented gradually;
- future plugins should be able to add suitable page actions without making the core menu confusing.

### Does Logseq do this? How?

Logseq provides some similar page-level actions through page menus, context menus, shortcuts, and file-related commands.

However, these actions are spread across different places, and some useful functions are difficult to discover. The goal is not to copy Logseq’s exact menu, but to give Tine a clearer and more complete page-level action center.

### Why — what's the use case?

Many useful Tine actions currently require users to remember shortcuts, open another menu, or find controls in different parts of the interface.

A visible “···” menu would make important functions easier to discover and reduce unnecessary navigation. It would be especially useful for:

- searching and replacing inside long pages;
- switching between rendered and source views;
- opening the same page in another pane or sidebar;
- copying page references, URLs, and file paths;
- collapsing or expanding large outlines;
- opening the Markdown file in another application;
- exporting a page;
- quickly reaching plugins, themes, settings, community, and feedback pages.

This would also give Tine a stable place for future page actions without adding more permanent buttons to the interface.

**Comment by martinkoutecky** [comment]
The first bounded page-actions slice is now on master in `3edc800` and is expected in the next patch release.

Pages now have an accessible ellipsis menu with the existing useful page actions gathered in one predictable place. The trigger and menu work with keyboard navigation and have a real Tauri/WebKit regression covering native clicks and keyboard use.

I am keeping this issue open because it is the broader capability tracker: future page-level actions should be evaluated and added coherently rather than turning the menu into an unstructured collection. The shipped first phase establishes the interaction and accessibility foundation.

Sol (working on Martin's behalf)

**Comment by EllisMorrow** [comment]
I tested it on Windows 11, and the feature works correctly in v0.6.1. If you have plans to add more functionality, you can continue improving it.

**Comment by martinkoutecky** [comment]
The bounded published-export link slice is now on `master` in `5aa9fc63` and is live in the public Guide at https://tine.page/guide/.

- With exactly one pane and one tab, the browser address follows the current page.
- The page menu now has **Copy page link**.
- A published block's context menu now has **Copy block link**. Block URLs use the block's graph-wide ID, so moving the block does not break its URL after the next export rebuild.
- Opening a page or block URL restores that target in the read-only app. With multiple panes or tabs, Tine keeps the last unambiguous URL instead of guessing which surface should own it.

The browser acceptance test covers automatic page URLs, the copy action, direct block-link startup, and the existing quiet-refocus behavior. I also verified those paths against the deployed public Guide.

I am keeping this issue open because it remains the broader page-menu tracker. This slice does not implement desktop/custom-protocol URLs from #181 or block selection/collapse from #548.

Astra (working on Martin's behalf)
